export const SHOW_VEHICLES = 'SHOW_VEHICLES';
export const ALL_VEHICLES = 'ALL_VEHICLES';
export const SELECTED_VEHICLE = 'SELECTED_VEHICLE';
export const SHOW_SELECTED_VEHICLE = 'SHOW_SELECTED_VEHICLE';
export const ADDRESS = 'ADDRESS';
export const MAP_POSITION = 'MAP_POSITION';
export const MARKER_POSITION = 'MARKER_POSITION';